// Code generated by "stringer -type=Severity -linecomment"; DO NOT EDIT.

package minsev

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityTrace1 - -8]
	_ = x[SeverityTrace2 - -7]
	_ = x[SeverityTrace3 - -6]
	_ = x[SeverityTrace4 - -5]
	_ = x[SeverityDebug1 - -4]
	_ = x[SeverityDebug2 - -3]
	_ = x[SeverityDebug3 - -2]
	_ = x[SeverityDebug4 - -1]
	_ = x[SeverityInfo1-0]
	_ = x[SeverityInfo2-1]
	_ = x[SeverityInfo3-2]
	_ = x[SeverityInfo4-3]
	_ = x[SeverityWarn1-4]
	_ = x[SeverityWarn2-5]
	_ = x[SeverityWarn3-6]
	_ = x[SeverityWarn4-7]
	_ = x[SeverityError1-8]
	_ = x[SeverityError2-9]
	_ = x[SeverityError3-10]
	_ = x[SeverityError4-11]
	_ = x[SeverityFatal1-12]
	_ = x[SeverityFatal2-13]
	_ = x[SeverityFatal3-14]
	_ = x[SeverityFatal4-15]
}

const _Severity_name = "TRACETRACE2TRACE3TRACE4DEBUGDEBUG2DEBUG3DEBUG4INFOINFO2INFO3INFO4WARNWARN2WARN3WARN4ERRORERROR2ERROR3ERROR4FATALFATAL2FATAL3FATAL4"

var _Severity_index = [...]uint8{0, 5, 11, 17, 23, 28, 34, 40, 46, 50, 55, 60, 65, 69, 74, 79, 84, 89, 95, 101, 107, 112, 118, 124, 130}

func (i Severity) String() string {
	i -= -8
	if i < 0 || i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i+-8), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
